#!/bin/bash

set -x

export LOG="$OPENSHIFT_LOG_DIR/build-$(date +%Y%m%d-%H%M%S).log"

export M2=$OPENSHIFT_DATA_DIR/apache-maven/bin
export JAVA_HOME=$OPENSHIFT_DATA_DIR/java
export PATH=$JAVA_HOME/bin:$M2:$PATH

cd $OPENSHIFT_REPO_DIR
touch "$LOG"
echo "Build starting at $(date)" >> "$LOG"
mvn -e -Dmaven.repo.local=$OPENSHIFT_DATA_DIR/.m2/repository -Dfinal.name=j2x-on-openshift clean package -Dmaven.test.skip=true -Pstandalone >> "$LOG" 2>&1 &
echo "Build finished at $(date)" >> "$LOG" 