#!/bin/bash
export M2=$OPENSHIFT_DATA_DIR/apache-maven-3.3.3/bin
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_51
export PATH=$JAVA_HOME/bin:$M2:$PATH

cd $OPENSHIFT_REPO_DIR
mvn -e -Dmaven.repo.local=$OPENSHIFT_DATA_DIR/.m2/repository clean package -Pstandalone
