#!/bin/bash
set -x
if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_51 ]
    then 
        cd $OPENSHIFT_DATA_DIR
        wget -c --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u51-b16/jdk-8u51-linux-x64.tar.gz
        tar xvf *.tar.gz 
        rm -f *.tar.gz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/apache-maven-3.3.3 ]
    then 
        cd $OPENSHIFT_DATA_DIR
        wget -c http://apache.websitebeheerjd.nl/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
        tar xvf *.tar.gz 
        rm -f *.tar.gz
fi
