#!/bin/bash

set -x

# OpenShift.com provides JDK 1.8 here: /etc/alternatives/java_sdk_1.8.0 
# Currently the version is openjdk-1.8.0.45-28.b13.el6_6.i386

export LOG=$OPENSHIFT_LOG_DIR/out.log

if [ ! -d $OPENSHIFT_DATA_DIR/java ]
    then 
        export JDK_VERSION=jdk1.8.0_51
        export JDK_INSTALL_VERSION=8u51-b16/jdk-8u51
        echo "Downloading Oracle $JDK_VERSION" > $LOG
        cd $OPENSHIFT_DATA_DIR
        wget -c --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/$JDK_INSTALL_VERSION-linux-x64.tar.gz
        tar xvf *.tar.gz
        mv $JDK_VERSION java 
        rm -f *.tar.gz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/apache-maven-3.3.3 ]
    then 
        export MVN_VERSION=3.3.3 
        echo "Downloading Maven $MVN_VERSION" > $LOG
        cd $OPENSHIFT_DATA_DIR
        wget -c http://apache.websitebeheerjd.nl/maven/maven-3/$MVN_VERSION/binaries/apache-maven-$MVN_VERSION-bin.tar.gz
        tar xvf *.tar.gz 
        mv apache-maven-$MVN_VERSION apache-maven
        rm -f *.tar.gz
fi
