#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

set -x

export LOG=$OPENSHIFT_LOG_DIR/app-$(date +%Y%m%d-%H%M%S).log

export M2=$OPENSHIFT_DATA_DIR/apache-maven/bin
export JAVA_HOME=$OPENSHIFT_DATA_DIR/java
export PATH=$JAVA_HOME/bin:$M2:$PATH

export IP_ADDRESS=$OPENSHIFT_DIY_IP
export PORT=$OPENSHIFT_DIY_PORT

cd $OPENSHIFT_REPO_DIR
touch "$LOG"
echo $(date) >> "$LOG"
nohup java -jar $OPENSHIFT_REPO_DIR/target/j2x-on-openshift-standalone.jar >> "$LOG" 2>&1 &
